cap label var r2005                "PMGSY road by 2005"
cap label var r2011                "PMGSY road by 2011"
cap label var yt2005               "Years of PMGSY road by 2005"
cap label var yt2011               "Years of PMGSY road by 2011"
cap label var con00                "Connected 2000"
cap label var pc01_pca_tot_p       "2001 population"
cap label var pc11_pca_tot_p       "2011 population"
cap label var pc01_pca_tot_work_p  "2001 total workers"
cap label var pc11_pca_tot_work_p  "2011 total workers"
cap label var irr_share            "Irrigation share"
cap label var ln_land              "Ln land area"
cap label var tdist                "Distance from town"
cap label var g_pop01              "Pop growth 1991-2001"
cap label var g_pop11              "Pop growth 2001-2011"
cap label var g_div                "Percent change in diversity"
cap label var cost2005usd          "Road cost (m USD) by 2005"
cap label var cost2011usd          "Road cost (m USD) by 2011"
cap label var sanc_year            "Year PMGSY sanctioned"
cap label var comp_year            "Year PMGSY completed"
cap label var primary_school       "Primary school"
cap label var electric             "Electrified"
cap label var app_pr               "Paved road (2001)"
cap label var treatment            "Treatment"
cap label var pop_left             "Population (below cutoff)"
cap label var pop_right            "Population (above cutoff)"
cap label var hl2_pop "maximum habitation population in village"
cap label var t "Road priority"
cap label var r2013 "New road"
cap label var r2012 "New road"
cap label var r2011 "New road"
cap label var left "2001 Pop * 1(Pop $<$ Cutoff)"
cap label var right "2001 Pop * 1(Pop $\geq$ Cutoff)"
cap label var leftright "2001 Pop - cutoff"
cap label var med_center "Medical center"
cap label var pc01_ill_share "Illiterate share"
cap label var pc01_lit_share "Literate share"
cap label var agrate_p01 "Ag emp share"
cap label var pc01_sc_share "Scheduled caste share"
cap label var electric2 "Electrified"
cap label var irr_share "Land irrigated share"
cap label var primary_school "Primary school"
cap label var tdist "Distance from nearest town (in km)"
cap label var bpl_inc_source_sub_share "Share of HH with subsistence agriculture as primary income source"
cap label var bpl_inc_250plus "Share of households earning 4 USD per month or above"

