/* create standardized names for merging */

/* clean names using rules */
foreach i in state_name district_name block_name village_name {
  name_clean `i', replace
  replace `i' = lower(subinstr(`i', " ", "", .))
  replace `i' = lower(subinstr(`i', ")", "", .))
  replace `i' = lower(subinstr(`i', "(", "", .))
  replace `i' = lower(subinstr(`i', "0", "a", .))
  replace `i' = lower(subinstr(`i', "-1", "i", .))
  replace `i' = lower(subinstr(`i', "-2", "ii", .))
  replace `i' = lower(subinstr(`i', "-3", "iii", .))
  replace `i' = lower(subinstr(`i', "-", "", .))
  count if regexm(`i', "[^0-9a-z,+=_]")
  while `r(N)' > 0 {
    replace `i' = regexr(`i', "[^0-9a-z,+=_]", "")
    count if regexm(`i', "[^0-9a-z,+=_]")
  }
}

/* manual replacements */

/* states */
replace state_name = "orissa" if state_name == "odisha"
replace state_name = "damananddiu" if state_name == "damandiu"
replace state_name = "uttarakhand" if state_name == "uttaranchal"
replace state_name = "andhrapradesh" if state_name == "telangana"
replace state_name = "jammuandkashmir" if state_name == "jammukashmir"
replace state_name = "dadraandnagarhaveli" if state_name == "dadranagarhaveli"

/* districts */
replace district_name = "mahbubnagar" if district_name == "mahaboobnagar" & state_name == "andhrapradesh"
replace district_name = "rangareddi" if district_name == "rangareddy" & state_name == "andhrapradesh"
replace district_name = "lohit" if district_name == "anjaw" & state_name == "arunachalpradesh"
replace district_name = "lowersubansiri" if district_name == "kurungkumey" & state_name == "arunachalpradesh"
replace district_name = "dibangvalley" if district_name == "lowerdibangvalley" & state_name == "arunachalpradesh"
replace district_name = "kamrup" if district_name == "kamruprural" & state_name == "assam"
replace district_name = "marigaon" if district_name == "morigaon" & state_name == "assam"
replace district_name = "nagaon" if district_name == "nowgaon" & state_name == "assam"
replace district_name = "northcacharhills" if district_name == "nchills" & state_name == "assam"
replace district_name = "jehanabad" if district_name == "jahanabad" & state_name == "bihar"
replace district_name = "kaimurbhabua" if district_name == "kaimurbhabhua" & state_name == "bihar"
replace district_name = "jehanabad" if district_name == "arwal" & state_name == "bihar"
replace district_name = "pashchimchamparan" if district_name == "westchamparan" & state_name == "bihar"
replace district_name = "purbachamparan" if district_name == "eastchamparan" & state_name == "bihar"
replace district_name = "purnia" if district_name == "purnea" & state_name == "bihar"
replace district_name = "saran" if district_name == "chaprasaran" & state_name == "bihar"
replace district_name = "sheikhpura" if district_name == "shekhpura" & state_name == "bihar"
replace district_name = "dantewada" if district_name == "bijapur" & state_name == "chhattisgarh"
replace district_name = "bastar" if district_name == "narayanpur" & state_name == "chhattisgarh"
replace district_name = "janjgirchampa" if district_name == "jangirchampa" & state_name == "chhattisgarh"
replace district_name = "koriya" if district_name == "koria" & state_name == "chhattisgarh"
replace district_name = "dadranagarhaveli" if district_name == "dadraandnagarhaveli" & state_name == "dadraandnagarhaveli"
replace district_name = "damananddiu" if district_name == "diu" & state_name == "damananddiu"
replace district_name = "damananddiu" if district_name == "daman" & state_name == "damananddiu"
replace district_name = "ahmadabad" if district_name == "ahmedabad" & state_name == "gujarat"
replace district_name = "dohad" if district_name == "dahod" & state_name == "gujarat"
replace district_name = "kachchh" if district_name == "kutch" & state_name == "gujarat"
replace district_name = "mahesana" if district_name == "mehsana" & state_name == "gujarat"
replace district_name = "surat" if district_name == "tapi" & state_name == "gujarat"
replace district_name = "thedangs" if district_name == "dangs" & state_name == "gujarat"
replace district_name = "mahendragarh" if district_name == "mohindergarh" & state_name == "haryana"
replace district_name = "sonipat" if district_name == "sonepat" & state_name == "haryana"
replace district_name = "lahulspiti" if district_name == "lahulandspiti" & state_name == "himachalpradesh"
replace district_name = "badgam" if district_name == "budgam" & state_name == "jammuandkashmir"
replace district_name = "baramula" if district_name == "baramulla" & state_name == "jammuandkashmir"
replace district_name = "lehladakh" if district_name == "leh" & state_name == "jammuandkashmir"
replace district_name = "punch" if district_name == "poonch" & state_name == "jammuandkashmir"
replace district_name = "rajauri" if district_name == "rajouri" & state_name == "jammuandkashmir"
replace district_name = "purbisinghbhum" if district_name == "eastsinghbhum" & state_name == "jharkhand"
replace district_name = "hazaribag" if district_name == "hazaribagh" & state_name == "jharkhand"
replace district_name = "kodarma" if district_name == "koderma" & state_name == "jharkhand"
replace district_name = "pakaur" if district_name == "pakur" & state_name == "jharkhand"
replace district_name = "palamu" if district_name == "palamau" & state_name == "jharkhand"
replace district_name = "sahibganj" if district_name == "sahebganj" & state_name == "jharkhand"
replace district_name = "dumka" if district_name == "jamtara" & state_name == "jharkhand"
replace district_name = "palamu" if district_name == "latehar" & state_name == "jharkhand"
replace district_name = "westsinghbhum" if district_name == "saraikelakharsawan" & state_name == "jharkhand"
replace district_name = "gumla" if district_name == "simdega" & state_name == "jharkhand"
replace district_name = "pashchimisinghbhum" if district_name == "westsinghbhum" & state_name == "jharkhand"
replace district_name = "bangalore" if district_name == "bangaloreu" & state_name == "karnataka"
replace district_name = "bangalorerural" if district_name == "bangalorer" & state_name == "karnataka"
replace district_name = "chikmagalur" if district_name == "chickmagalur" & state_name == "karnataka"
replace district_name = "kolar" if district_name == "chickballapur" & state_name == "karnataka"
replace district_name = "bangalorerural" if district_name == "ramnagar" & state_name == "karnataka"
replace district_name = "gulbarga" if district_name == "yadgiri" & state_name == "karnataka"
replace district_name = "jhabua" if district_name == "alirajpur" & state_name == "madhyapradesh"
replace district_name = "shahdol" if district_name == "anuppur" & state_name == "madhyapradesh"
replace district_name = "guna" if district_name == "ashoknagar" & state_name == "madhyapradesh"
replace district_name = "eastnimar" if district_name == "burhanpur" & state_name == "madhyapradesh"
replace district_name = "eastnimar" if district_name == "khandwa" & state_name == "madhyapradesh"
replace district_name = "westnimar" if district_name == "khargone" & state_name == "madhyapradesh"
replace district_name = "mandsaur" if district_name == "mandsour" & state_name == "madhyapradesh"
replace district_name = "narsimhapur" if district_name == "narsighpur" & state_name == "madhyapradesh"
replace district_name = "sheopur" if district_name == "seopur" & state_name == "madhyapradesh"
replace district_name = "sidhi" if district_name == "singrauli" & state_name == "madhyapradesh"
replace district_name = "umaria" if district_name == "umria" & state_name == "madhyapradesh"
replace district_name = "ahmadnagar" if district_name == "ahmednagar" & state_name == "maharashtra"
replace district_name = "amravati" if district_name == "amrawati" & state_name == "maharashtra"
replace district_name = "bid" if district_name == "beed" & state_name == "maharashtra"
replace district_name = "buldana" if district_name == "buldhana" & state_name == "maharashtra"
replace district_name = "gondiya" if district_name == "gondia" & state_name == "maharashtra"
replace district_name = "raigarh" if district_name == "raigad" & state_name == "maharashtra"
replace district_name = "sangli" if district_name == "sangali" & state_name == "maharashtra"
replace district_name = "jaintiahills" if district_name == "jaintia" & state_name == "meghalaya"
replace district_name = "tuensang" if district_name == "kiphire" & state_name == "nagaland"
replace district_name = "tuensang" if district_name == "longleng" & state_name == "nagaland"
replace district_name = "kohima" if district_name == "peren" & state_name == "nagaland"
replace district_name = "anugul" if district_name == "angul" & state_name == "orissa"
replace district_name = "balangir" if district_name == "bolangir" & state_name == "orissa"
replace district_name = "baleshwar" if district_name == "balasore" & state_name == "orissa"
replace district_name = "baudh" if district_name == "boudh" & state_name == "orissa"
replace district_name = "debagarh" if district_name == "deogarh" & state_name == "orissa"
replace district_name = "jagatsinghapur" if district_name == "jagatsinghpur" & state_name == "orissa"
replace district_name = "jajapur" if district_name == "jajpur" & state_name == "orissa"
replace district_name = "kandhamal" if district_name == "phulbanikandhamal" & state_name == "orissa"
replace district_name = "kendujhar" if district_name == "keonjhar" & state_name == "orissa"
replace district_name = "khordha" if district_name == "khurda" & state_name == "orissa"
replace district_name = "nabarangapur" if district_name == "nawarangpur" & state_name == "orissa"
replace district_name = "nuapada" if district_name == "nuapara" & state_name == "orissa"
replace district_name = "sonapur" if district_name == "sonepur" & state_name == "orissa"
replace district_name = "sangrur" if district_name == "barnala" & state_name == "punjab"
replace district_name = "firozpur" if district_name == "fazilka" & state_name == "punjab"
replace district_name = "firozpur" if district_name == "ferozepur" & state_name == "punjab"
replace district_name = "rupnagar" if district_name == "mohali" & state_name == "punjab"
replace district_name = "muktsar" if district_name == "mukatsar" & state_name == "punjab"
replace district_name = "nawanshahr" if district_name == "nawashahar" & state_name == "punjab"
replace district_name = "gurdaspur" if district_name == "pathankot" & state_name == "punjab"
replace district_name = "amritsar" if district_name == "tarntaran" & state_name == "punjab"
replace district_name = "rupnagar" if district_name == "ropar" & state_name == "punjab"
replace district_name = "ganganagar" if district_name == "sriganganagar" & state_name == "rajasthan"
replace district_name = "chittaurgarh" if district_name == "pratapgarh" & state_name == "rajasthan"
replace district_name = "kancheepuram" if district_name == "kanchipuram" & state_name == "tamilnadu"
replace district_name = "dharmapuri" if district_name == "krishnagiri" & state_name == "tamilnadu"
replace district_name = "ramanathapuram" if district_name == "ramanadhapuram" & state_name == "tamilnadu"
replace district_name = "sivaganga" if district_name == "sivagangai" & state_name == "tamilnadu"
replace district_name = "coimbatore" if district_name == "tiruppur" & state_name == "tamilnadu"
replace district_name = "thiruvallur" if district_name == "tiruvallur" & state_name == "tamilnadu"
replace district_name = "thiruvarur" if district_name == "tiruvarur" & state_name == "tamilnadu"
replace district_name = "thoothukkudi" if district_name == "tuticorin" & state_name == "tamilnadu"
replace district_name = "viluppuram" if district_name == "villupuram" & state_name == "tamilnadu"
replace district_name = "virudhunagar" if district_name == "virudunagar" & state_name == "tamilnadu"
replace district_name = "garhwal" if district_name == "pauri" & state_name == "uttarakhand"
replace district_name = "hardwar" if district_name == "haridwar" & state_name == "uttarakhand"
replace district_name = "tehrigarhwal" if district_name == "tehri" & state_name == "uttarakhand"
replace district_name = "budaun" if district_name == "badaun" & state_name == "uttarpradesh"
replace district_name = "bulandshahar" if district_name == "bulandshahr" & state_name == "uttarpradesh"
replace district_name = "gautambuddhanagar" if district_name == "gbnagar" & state_name == "uttarpradesh"
replace district_name = "ghaziabad" if district_name == "hapur" & state_name == "uttarpradesh"
replace district_name = "jyotibaphulenagar" if district_name == "jbfnagar" & state_name == "uttarpradesh"
replace district_name = "kheri" if district_name == "lakhimpurkherii" & state_name == "uttarpradesh"
replace district_name = "mahrajganj" if district_name == "maharajganj" & state_name == "uttarpradesh"
replace district_name = "santkabirnagar" if district_name == "sknagar" & state_name == "uttarpradesh"
replace district_name = "santravidasnagarbhadohi" if district_name == "srnagarbhadohi" & state_name == "uttarpradesh"
replace district_name = "shrawasti" if district_name == "shravasti" & state_name == "uttarpradesh"
replace district_name = "siddharthnagar" if district_name == "siddharathnagar" & state_name == "uttarpradesh"
replace district_name = "sonbhadra" if district_name == "sonebhadra" & state_name == "uttarpradesh"
replace district_name = "barddhaman" if district_name == "burdwan" & state_name == "westbengal"
replace district_name = "darjiling" if district_name == "darjeeling" & state_name == "westbengal"
replace district_name = "haora" if district_name == "howrah" & state_name == "westbengal"
replace district_name = "hugli" if district_name == "hooghly" & state_name == "westbengal"
replace district_name = "kochbihar" if district_name == "coochbehar" & state_name == "westbengal"
replace district_name = "maldah" if district_name == "malda" & state_name == "westbengal"
replace district_name = "medinipur" if district_name == "paschimmedinipur" & state_name == "westbengal"
replace district_name = "medinipur" if district_name == "purbamedinipur" & state_name == "westbengal"
replace district_name = "puruliya" if district_name == "purulia" & state_name == "westbengal"
replace district_name = "darjiling" if district_name == "siligurimp" & state_name == "westbengal"
replace district_name = "northtwentyfourparganas" if district_name == "northii4parganas" & state_name == "westbengal"
replace district_name = "southtwentyfourparganas" if district_name == "southii4parganas" & state_name == "westbengal"
replace district_name = "northtwentyfourparganas" if district_name == "northii4parganas" & state_name == "westbengal"
replace district_name = "southtwentyfourparganas" if district_name == "southii4parganas" & state_name == "westbengal"



